version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: atypic
      WORDPRESS_DEBUG: 1
    volumes:
      - ./:/var/www/html/wp-content/themes/atypic

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: atypic
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_USER: admin
      PMA_PASSWORD: password
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

volumes:
  wordpress:
  db: