version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8880:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: atypic
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html/
      - ../:/var/www/html/wp-content/themes/atypic
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./debug.log:/var/www/html/wp-content/debug.log

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: atypic
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_USER: admin
      PMA_PASSWORD: admin
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin

volumes:
  db:
  wordpress: